select  BODY -> PAYLOAD -> VALUE -> COUNTRY from  COVID_STREAM EMIT CHANGES;


select  BODY -> PAYLOAD -> VALUE -> COUNTRY as country, SUM( BODY -> PAYLOAD -> VALUE -> NewConfirmed) as NEW_CONFIRMED 
from  COVID_STREAM 
WINDOW TUMBLING (SIZE 1 MINUTE)
GROUP BY BODY -> PAYLOAD -> VALUE -> COUNTRY
EMIT CHANGES;
